### ISSUE TITLE
Support Pleroma

### ISSUE THREAD

**Issue by oct2pus** [bleakgrey/tootle#228]
⚠️ Please try to fill in every blank. Keep the information clear and concise.

#### What should happen:
- Sent to Pleroma oauth request page.
__

#### What happened instead:
- Recieved bad request error.
__

#### How to reproduce:
1. Click Add New Account
2. Attempt to connect to a Pleroma Community

#### Screenshots (if applicable):
![Screenshot from 2020-09-10 22-05-23](https://user-images.githubusercontent.com/30452393/92850432-0a414780-f3b2-11ea-92b9-689085722593.png)
__

#### Build context:
 - **Distro:**: Arch
 - **App version:**: 1.0-alpha1
 - **Build type:** Built from [PKGBUILD](https://gist.github.com/oct2pus/051e3a507427cd3507677578b942ffb3)

#### Logs:
*(Terminal logs are often invaluable. If you can, launch the app from terminal with `com.github.bleakgrey.tootle` and paste the output here)*

#### Additional info (if needed):

I feel like I remember older versions of tootle successfully being used with pleroma. This might be a regression.
__

**Comment by oct2pus** [comment]
tested against old outdated version by mistake

**Comment by oct2pus** [comment]
retested against current 1.0-alpha1, still occurs. here is an error log.
```** Message: 23:19:55.377: NewAccount.vala:76: Reset state
** Message: 23:20:02.965: NewAccount.vala:116: Checking instance URL
** Message: 23:20:02.965: NewAccount.vala:131: Registering client

** (tootle:141945): WARNING **: 23:20:02.971: NewAccount.vala:62: Failed to execute child process “xdg-mime” (No such file or directory)

** (tootle:141945): CRITICAL **: 23:20:02.972: string_to_string: assertion 'self != NULL' failed
** Message: 23:20:02.972: Network.vala:50: POST: https://catgirl.science/api/v1/apps?redirect_uris=urn:ietf:wg:oauth:2.0:oob&client_name=Tootle&scopes=read%20write%20follow&website=https://github.com/bleakgrey/tootle

** (tootle:141945): WARNING **: 23:20:03.651: NewAccount.vala:90: Server returned an error   400: Bad Request```

**Comment by bleakgrey** [comment]
Tootle was never really supposed to work with Pleroma, so its possible working with other platforms is purely coincidental due to similar APIs.

Even if the auth process is adapted, Tootle will still have a hard time parsing Pleroma's markup in user posts.

Summoning @alexcleac to evaluate the amount of work needed to make Tootle support Pleroma.

**Comment by cleac** [comment]
It is actually a strange behavior. I had some issues like that, but they have gone after I removed adding access token at some requests at that stage. Maybe they should help @bleakgrey 

What version of pleroma do you use, @oct2pus?

**Comment by bleakgrey** [comment]
It looks like @dec05eba managed to fix the authentication issue :tada:

If we think of a way to remove unsupported HTML tags in user posts, Tootle should behave nicely with Pleroma instances semi-decently.

**Comment by oct2pus** [comment]
> What version of pleroma do you use, @oct2pus?
    Backend Version
        2.1.1-42-g713d944e

    Frontend Version
        938887ef

**Comment by dec05eba** [comment]
> If we think of a way to remove unsupported HTML tags in user posts, Tootle should behave nicely with Pleroma instances semi-decently.

I have a commit for that as well. I'll make a pull request after the authentication fix is merged

**Comment by BrainBlasted** [comment]
What's the status of this? The version from Flathub still cannot log in

**Comment by nebocamin** [comment]
I'm getting a "400 Bade Request" after inserting my pleroma domain.

**Comment by bleakgrey** [comment]
Are you using the `master` branch?

**Comment by BrainBlasted** [comment]
Everything seems to work fine on the development branch now.

**Comment by nebocamin** [comment]
sorry, my fault. its working... will now try to build it for mobian on pinephone.
